language: csharp
solution: PredicateMaps/PredicateMaps.sln
install:
  - nuget restore PredicateMaps/PredicateMaps.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug PredicateMaps/PredicateMaps.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./PredicateMapsTests/bin/Debug/PredicateMapsTests.dll