//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examples.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Examples.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrown exception was Argument Exception..
        /// </summary>
        internal static string ArgumentExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to interpret type name parameter. The ExceptionThrower was not able to create an instance of the required type..
        /// </summary>
        internal static string IsUnrecognisedTypeException {
            get {
                return ResourceManager.GetString("IsUnrecognisedTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrown exception was Not Implemented Exception but message indicates that method will be implemented in a later release..
        /// </summary>
        internal static string NotCurrentlyImplementedExceptionMessage {
            get {
                return ResourceManager.GetString("NotCurrentlyImplementedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrown exception was Not Implemented Exception..
        /// </summary>
        internal static string NotImplementedExceptionMessage {
            get {
                return ResourceManager.GetString("NotImplementedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrown exception was Null Reference Exception..
        /// </summary>
        internal static string NullReferenceExceptionMessage {
            get {
                return ResourceManager.GetString("NullReferenceExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception type passed for filtering was not of a recognised type..
        /// </summary>
        internal static string UnableToHandlePassedException {
            get {
                return ResourceManager.GetString("UnableToHandlePassedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered type name {0} was not recognised for excpetion filtering..
        /// </summary>
        internal static string UnrecognisedExceptionType {
            get {
                return ResourceManager.GetString("UnrecognisedExceptionType", resourceCulture);
            }
        }
    }
}
